# Generated by Django 2.1.2 on 2018-10-16 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_squashed_0009_auto_20181017_0212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='society',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
