# Generated by Django 2.1.2 on 2018-10-14 11:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='society',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='user',
            name='otp_expiry',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
    ]
