# Generated by Django 2.1.2 on 2018-10-23 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_society_published_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='events',
        ),
        migrations.AddField(
            model_name='event',
            name='sessions',
            field=models.CharField(blank=True, choices=[('18-19', '2018-2019'), ('19-20', '2019-2020')], max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='event', to='api.Tag'),
        ),
    ]
