# Generated by Django 2.1.2 on 2018-10-14 15:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20181014_1146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.IntegerField(null=True, unique=True, validators=[django.core.validators.RegexValidator(message='Phone number must be of 10 digits.', regex='^\\d{10}$')]),
        ),
    ]
