# Generated by Django 2.1.2 on 2018-10-23 14:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20181023_1925'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='event',
            name='start_time',
        ),
        migrations.AlterField(
            model_name='event',
            name='end_day',
            field=models.DateTimeField(help_text='End date and time of the event', verbose_name='End date and time of the event'),
        ),
        migrations.AlterField(
            model_name='event',
            name='society',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Society'),
        ),
        migrations.AlterField(
            model_name='event',
            name='start_day',
            field=models.DateTimeField(help_text='Start date and time of the event', verbose_name='Start date and time of the event'),
        ),
        migrations.AlterField(
            model_name='event',
            name='tags',
            field=models.ManyToManyField(blank=True, to='api.Tag'),
        ),
    ]
