# Generated by Django 2.1.2 on 2018-10-23 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20181023_2008'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='sessions',
        ),
        migrations.AddField(
            model_name='event',
            name='session',
            field=models.CharField(blank=True, choices=[('18', '2018-2019'), ('19', '2019-2020')], max_length=2, null=True),
        ),
    ]
