# Generated by Django 2.1.2 on 2018-10-16 20:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20181016_2000'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='phone',
            field=models.CharField(max_length=10, null=True, validators=[django.core.validators.RegexValidator(message='Invalid phone number.', regex='^\\d{10}$')]),
        ),
        migrations.AddField(
            model_name='tag',
            name='events',
            field=models.ManyToManyField(blank=True, related_name='tags', to='api.Event'),
        ),
        migrations.AlterField(
            model_name='event',
            name='contact_person',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='name',
            field=models.TextField(max_length=80),
        ),
        migrations.AlterField(
            model_name='society',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='society',
            name='phone',
            field=models.CharField(max_length=10, null=True, validators=[django.core.validators.RegexValidator(message='Invalid phone number.', regex='^\\d{10}$')]),
        ),
    ]
