# Generated by Django 2.1.2 on 2018-10-26 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20181025_0036'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='phone',
            new_name='contact_phone',
        ),
        migrations.AddField(
            model_name='society',
            name='type',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='society',
            name='department_name',
            field=models.CharField(max_length=40),
        ),
    ]
