# Generated by Django 2.1.2 on 2018-10-27 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20181027_0344'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='contact_phone',
            new_name='contact_number',
        ),
        migrations.AlterField(
            model_name='event',
            name='end_day',
            field=models.DateTimeField(verbose_name='End date and time'),
        ),
        migrations.AlterField(
            model_name='event',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='event',
            name='start_day',
            field=models.DateTimeField(help_text='Format: HH:MM:SS', verbose_name='Start date and time'),
        ),
    ]
