# Generated by Django 2.1.2 on 2018-10-28 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20181027_1729'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='fcm_token',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='start_day',
            field=models.DateTimeField(help_text='Time Format: HH:MM:SS', verbose_name='Start date and time'),
        ),
    ]
