# Generated by Django 2.1.2 on 2018-11-21 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_auto_20181028_2148'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='otp',
            field=models.IntegerField(blank=True, default='696217', null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='verified',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
